{% set name = "kml2geojson" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kml2geojson-{{ version }}.tar.gz
  sha256: 1340448c64f09ecf646cd7ddab8c81f27cba78b2118c2eb7474ead095bbdedf7

build:
  number: 0
  noarch: python
  entry_points:
    - k2g = kml2geojson.cli:k2g
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.1

test:
  imports:
    - kml2geojson
  commands:
    - pip check
    - k2g --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/kml2geojson/
  summary: A Python library to covert KML files to GeoJSON files
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ickc
